/*******************************************************************************
 * Waveshare ESP32-S3-Touch-LCD-7 LVGL 9.3 Squareline Launcher
 *
 * Demonstrates the display and touch libraries for the
 * Waveshare ESP32-S3-Touch-LCD-7 development board.
 *
 * Requires the following libraries:
 *   - chipguy_ESP32S3_Touch_LCD_7_display  (ST7262 800x480 RGB LCD + GT911 touch, this library)
 *   - chipguy_ESP32-S3-Touch-LCD-7_board   (shared I2C bus + expander; a dependency)
 *   - lvgl 9
 *
 * Arduino IDE Board Settings:
 *   - Board: ESP32S3 Dev Module
 *   - PSRAM: OPI PSRAM
 *   - Upload Speed: 460800
 *   - Flash Size: 8 MegaBytes (64 megabits)
 *   - USB CDC On Boot: Enabled
 *
 * Copyright (c) 2025 chipguyhere
 * MIT License
 ******************************************************************************/

// This is built for LVGL 9.3, which Squareline can generate UI's for.
// It's important for the version numbers to match, even if it's not newest.
#include "lv_conf.h"
#include "lvgl.h"
#include "lv_setup.hpp"

// Fonts
// The Montserrat font is built into LVGL in multiple sizes, each size takes up memory.
// We enable the 14 point font as a default font.
#define LV_FONT_MONTSERRAT_14 1
// need other sizes?  Edit lv_conf.h where they are turned off (0) and turn them on (1)

// The folder of UI files generated by Squareline should be a src subdirectory in the sketch folder.
// Simply DELETE all of the example files, and "Export UI files" from Squareline.
// Using the Arduino TFT_eSPI profile from Squareline works
// Required settings: 800x480, 16-bit color depth, no rotation or offset.
#include "src/ui.h"


void setup() {
    // Note: USB serial output on this device is Serial0,
    // and "USB CDC On Boot" must be enabled to see anything
    Serial0.begin(115200);

    // Initialize display, touch, and LVGL.
    // Rotation: lv_setup.begin(180) for an upside-down panel, or begin(90) /
    // begin(270) for portrait (480x800).  See the README.
    lv_setup.begin();
    Serial0.printf("LVGL initialized with %dx%d touchscreen\n", display.width(), display.height());

    // Start the Squareline application
    ui_init();
}


void loop() {
    // Give control to LVGL objects created by Squareline application
    lv_timer_handler(); /* let the GUI do its work */
    delay(5);
}
